### ISSUE TITLE
Button for picking a random Artifact

### ISSUE THREAD

**Issue by MightyW0lf** [KingEnderBrine/-RoR2-RandomCharacterSelection#1]
Add a button for picking a **single** random artifact.

## Why?
Sometimes I want to spice up a run by adding a little something extra. But if I'm playing a modpack with XX more artifacts and want to play with just a few random ones, the random button doesn't serve well - as it selects way more artifacts than I want in that situation.

**Comment by KingEnderBrine** [comment]
It's not suitable for this mod. But there is a mod called [ArtifactsRandomizer](https://thunderstore.io/package/KingEnderBrine/ArtifactsRandomizer/). It has configs but I suppose you only want to select a random artifact at the start of a run. I just added that option in it. So, to do exactly what you want you would need in `Main` section set `RandomizationMode = Weight` and `OnlyAtRunStart = true`, in `Weight` section set `MaxCount = 1` and `MinCount = 1`

**Comment by MightyW0lf** [comment]
Amazing, thanks!

First when I saw this I was a bit worried, because I'm also playing with [Artifact of the King](https://thunderstore.io/package/Blobface/Artifact_of_the_King/) always on. But the weight (setting Artifact of the King's weight to a high amount so it gets always selected) + min/max count (setting both to 2) configuration did the job exactly as I wanted :)

**Comment by KingEnderBrine** [comment]
Small tip, you can add artifacts to a `BlackList` and the mod will not touch these artifacts. You can then enable or disable these artifacts by yourself just like you would in vanilla. That way you can be sure that some artifacts are selected and others are randomized
